version: '3'
services:
  postgres:
  image: postgres:13
  container_name: postgres_db
  enviroment:
    POSTGRES_USER= postgres
    POSTGRES_PASSWORD= postgres
    # POSTGRES_DB: postgres
  ports:
      - "5432:5432"
  volumes:
      - postgres_data:/var/lib/postgressql/postgres_data

volumes:
  postgres_data: